### ISSUE TITLE
缺少文件/momotalk

### ISSUE THREAD

**Issue by qianxinwanjiu** [U1805/momotalk#12]
缺少文件
根目录下缺少momotalk这个文件夹以及所以文件

**Comment by U1805** [comment]
请问可以给出详细一些的描述吗，我在重新启动的过程中没能复现你的问题。

**Comment by qianxinwanjiu** [comment]
直接使用仓库代码Git clone到本地后 部署发现白屏 后参考示例站点发现缺少momotalk这个文件夹，从您的示例站点中我找到了这些文件，添加这些文件并修改根目录下的index.html后才可正常访问

修改后的index.html内容如下：
`<!DOCTYPE html>
<html lang="zh">

<head>
  <meta charset="UTF-8">
  <link rel="icon" href="/momotalk/favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Momotalk</title>
  <script type="module" crossorigin src="/momotalk/assets/index-49e3487f.js"></script>
  <link rel="stylesheet" href="/momotalk/assets/index-eb798019.css">
</head>

<body>
  <div id="app"></div>

</body>

</html>

`
正确目录：
![image](https://github.com/U1805/momotalk/assets/111267078/c89130fc-e188-4b97-a33a-a46b4cecc5ab)
原目录格式：
![image](https://github.com/U1805/momotalk/assets/111267078/1c737ebf-a880-49f7-9dd1-240ddd80db23)
修改前，打开是这样的：
![image](https://github.com/U1805/momotalk/assets/111267078/718c3060-c895-4b6c-a7d0-070f973d49cf)

这是我修改后的站点：
https://momotalk.cn/

**Comment by qianxinwanjiu** [comment]
稍后我会在我搭建的站点添加版权信息

**Comment by U1805** [comment]
代码并没有问题，

1. 你所说的 `momotalk` 文件夹就是项目根目录，
图中看到你的根目录是 `momotalk-main` 猜测你可能通过 download zip 的方式得到代码而非 git clone
```bash
git clone git@github.com:U1805/momotalk.git
```
2. 如果你希望代码调试，请执行 `npm run dev` 运行开发环境
如果你希望直接部署，请执行 `npm run build` 打包项目，然后部署 `docs` 文件夹

希望对你有帮助
