### ISSUE TITLE
[feature] Chat history export/import

### ISSUE THREAD

**Issue by nfnfgo** [U1805/momotalk#17]
This is really a great project and i love the features like system msg and event message!

Seems that currently the chat history is stored on the localStorage of the browser, do you consider to add an **chat history export/import feature** (for example allow users to export as json or whatever other formats, and allow users to import chat history from files) so that users can save or edit their chats in any other browsers or devices?

**Comment by U1805** [comment]
Yes, this feature is indeed valuable in certain situations. Thank you for your suggestion and for expressing your appreciation for the project!

I agree that the current interface might have a few too many buttons. I'm considering adding a "Settings" button to streamline the user interface, and the "Import/Export" feature will likely be included within that section to keep things organized. I'll work on implementing this feature soon.

Thank you again for your feedback!

**Comment by nfnfgo** [comment]
That sounds great and I'm looking forward to the new interface design!

And also I think that exported file could also contains some other info like selected characters, custom imgs that user added to the chat (if exists) and other alternative info.

Actually imo maybe it's a better way to consider all the info such as _selected/used students_, _custom characters_, _added custom imgs_ and other info into a _project info_ as a whole, so when user import/export data, they are actually import/export the whole project info but not only a list of the info of each messages.

**Comment by U1805** [comment]
This feature is done! (σ`∀´)σ
