### ISSUE TITLE
你好，我们社团用你的momotalk做了一个同人本

### ISSUE THREAD

**Issue by Anegg14** [U1805/momotalk#19]
你好，我们社团用你的momotalk做了一个同人本，想要把你放在尾页的特别鸣谢。
这是我们社团的cpp主页：https://www.allcpp.cn/c/350672.do
如果可以的话，希望可以留一个你的地址，我把这届cp30会卖的本子和制品都送你一份！
我的邮箱是：tea14@qq.com

**Comment by U1805** [comment]
非常感谢选择使用这个项目。能够被列为尾页的特别鸣谢对象，我深感荣幸。
期待收到你们制作的本子和制品，并感谢你们的慷慨赠送！
我会尽快联系你的邮箱。如果有任何其他问题或需要进一步沟通，随时与我联系。
再次感谢你们对这个momotalk的支持，祝愿你们的社团活动取得圆满成功！(*´∀`)~♥
