### ISSUE TITLE
the event bubble title's text is colored white

### ISSUE THREAD

**Issue by DrunkenPipe** [U1805/momotalk#26]
![image](https://github.com/U1805/momotalk/assets/170069732/e0d4bbb4-08c6-4cfc-9f02-fbe98c184283)
![image](https://github.com/U1805/momotalk/assets/170069732/67c76679-1dbf-4d3c-b70c-0dc33e9d8db9)
please change the event title text color above the testing word to be black please!

**Comment by DrunkenPipe** [comment]
![image](https://github.com/U1805/momotalk/assets/170069732/5fad5908-e3e4-4694-b7d5-fea9138a79fe)
it look like inspect element can change text color, should i close this?

**Comment by U1805** [comment]
Thank you for bringing this to my attention. I haven't encountered this issue on my browser. Could you please provide more details about your browser and its version? Regarding your question about closing the issue, let's keep it open for now. I'll look into fixing this problem later. Would you mind testing the bug again when I've made the adjustments? Thank you for your patience and cooperation.

**Comment by U1805** [comment]
I've made some adjustments. Could you please test again to see if the issue still persists? Your feedback would be greatly appreciated. (*ﾟ∀ﾟ*)

**Comment by DrunkenPipe** [comment]
hi sorry for late reply, it fixed! thank you so much.
