### ISSUE TITLE
settings text colours are gray/white + text new line issue

### ISSUE THREAD

**Issue by DrunkenPipe** [U1805/momotalk#27]
![image](https://github.com/U1805/momotalk/assets/170069732/61cd8eb6-1b51-448b-b8b5-8aad5db1ce9e)
![image](https://github.com/U1805/momotalk/assets/170069732/10f1c276-36ed-409d-9ada-391546f3089a)
this is all i could find on this text colour issue for now
if the text colour issue isn't consistent then here my browser. 
my browser is edge Version 124.0.2478.105, yes i use edge please don't bully me.
i tested it on mobile and it seem to work normally.
![image](https://github.com/U1805/momotalk/assets/170069732/e412d363-863f-423f-be57-73123f008bb7)
on the text newline issue, when the word are automatically newline'd they don't go down a line together but rather are chopped into half, this can be work around by simply press enter before the word "time" but it usually a hassle when doing it alot.
the mobile device has this problem alot due to it small scaling.

**Comment by U1805** [comment]
Hi, sorry for only addressing the issue now. I believe I've found the source of the text color issue. The project was initially set up with a `base.css` style file, which included the control of text color based on the light/dark theme of the system. As I always use the light theme, I didn't notice this and continued to use it. However, your system may be on dark mode, hence texts without set color turn out white. 

Not to fret, as it's all fixed now. I have removed the system theme related code from the `base.css`, and the issue has been resolved. 😎 

Moreover, thank you for pointing out the text new line issue, it's been fixed as well. please give it a test run!

**Comment by DrunkenPipe** [comment]
nice! sorry for late reply, i will report my final issue that have been bugging me in mobile soon and i will think that is all done!
