### ISSUE TITLE
mobile's control buttons problem.

### ISSUE THREAD

**Issue by DrunkenPipe** [U1805/momotalk#28]
![image](https://github.com/U1805/momotalk/assets/170069732/cd3882e0-6f24-4f87-8271-4281ba61aa30)
the bad scaling of the mobile version for me personally has made it so the gray/black momotalk buttons below are obstructed. 
You can still press it.
![image](https://github.com/U1805/momotalk/assets/170069732/2e6d805a-7539-4ee9-aee7-781deac1d699)
however do note that when i swipe up for the phone functionality buttons, the momotalk buttons jumped up too!
but it is still obstructed by the phone functionality buttons. **which made me wonder if this is really a scaling problem.**

**Comment by U1805** [comment]
i suspect that the phone browser's address bar is taking up some space, causing the buttons below to be pushed out of the visible area. Can you please try setting your browser to full screen mode and let me know the result, it would be helpful in narrowing down the bug.

**Comment by U1805** [comment]
for example, you can try swiping up on the area where the top title bar and search bar are, the address bar might hide itself. Alternatively, you can check if there's a full screen mode option or something in your browser.

**Comment by U1805** [comment]
Hey! i recreated the same issue as yours on my another mobile browser, and i believe the bug is indeed due to the address bar. Good news though, i've managed to fix the problem, and it is working well on my device now. Give it a test run! σ`∀´)σ

**Comment by DrunkenPipe** [comment]
hi, sorry for always late reply since i don't check on this site much, the issue has been fixed! 
btw about the address bar thing, i can never make it hide away before posting this issue. nothing work on making it go away XD.
this will probably be my last issue, thank you so much for making the site!
![image](https://github.com/U1805/momotalk/assets/170069732/6083612c-a01c-49dd-b10d-17ea2e96ddc4)
