### ISSUE TITLE
Browser’s Zoom Level Bug / 浏览器缩放错误

### ISSUE THREAD

**Issue by DrunkenPipe** [U1805/momotalk#30]
this bug didn't happen at the beginning but it somehow popped up midway during today session.
what it supposed to show
![image](https://github.com/U1805/momotalk/assets/170069732/bd77ad06-c71c-48fa-ab2a-689aace9bdb4)
what the downloaded image show after i use the website download function.
![Momotalk-1716353318851](https://github.com/U1805/momotalk/assets/170069732/84dc1e43-bbe5-4c17-82c1-6601db92627f)
however it seem that the other browser with a clean slate/no data is fine.
it clear that my momotalk site is corrupted in some way, i tried to delete it cookies but the momotalk dont contain any cookies itself.
please add a function to "factory reset" momotalk to it original state. thank you

**Comment by U1805** [comment]
Thank you for reporting this issue. I was able to reproduce the error on my browser. It seems that the problem may be related to browser zoom settings.

When I set my browser to 90% zoom, the result is as follows:
![图片](https://github.com/U1805/momotalk/assets/45514638/06c6dd3f-f195-4ca9-8eae-cac033902f03)
![图片](https://github.com/U1805/momotalk/assets/45514638/0e5e22a1-6ed2-4fb2-b595-f17542fb9b59)

To resolve this, you can try resetting the zoom level in your browser settings. If the issue persists, please let us know, and we'll investigate further.

**Comment by DrunkenPipe** [comment]
is there any other way to fix this rather than reset the zoom? you will probably need to put up a small notice for the zoom bug when they download the image.
and the original zoom size is just really too big for me（；´д｀）ゞ

**Comment by U1805** [comment]
maybe you could try using the **full-screen mode**, enabling this feature in the settings ("gear" icon in the top-right corner) . in full-screen mode, the screen (canvas) enlarges, which effectively reduces the size of all components relative to the screen size, including dialog boxes, avatars, ... 

if this is not fully useful, please let me know, and I'll explore adding a zoom functionality later on to better accommodate your needs.

**Comment by DrunkenPipe** [comment]
you can add the Zoom feature anytime, now i think you should tell the user to default zoom first b4 they download the images file, i did a consecutive work of multiple images the other day and only realized the bug when im done, have to manually write and capture all of the momotalk again ╚(•⌂•)╝

**Comment by U1805** [comment]
done. it is working well on my device now. Give it a run! σ`∀´)σ

- [x] notify users to confirm before downloading image files if their browser is not set to 100% zoom.
- [x] implement the zoom feature that can be enabled in the settings⚙.

**Comment by DrunkenPipe** [comment]
the browser still notify the user even if the browser is set to 100% zoom, please fix! /_ \

**Comment by U1805** [comment]
i made a basic mistake by using "==" to compare a floating point number with an integer (radio === 1). Clearly, at 100% zoom, the ratio could be something like 1.004. i have corrected this. (ノдT) 

However, i discovered a bigger issue: my detection method only works for Edge and Chrome but is ineffective for Firefox. 

i need to find a better detection method that works across all browsers, but it seems quite [challenging](https://css-tricks.com/can-javascript-detect-the-browsers-zoom-level/). Therefore, even if it runs on your Edge browser, please do not close this issue yet.  ｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡

**Comment by U1805** [comment]
I have decided to stop looking for a method that supports all browsers, at least for now. Unfortunately, I couldn't find a way to detect zoom changes for users on other browsers.  ｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡

I pinned this issue, hoping that affected users will see it. 

If it works correctly on your browser, I will close this issue.

**Comment by DrunkenPipe** [comment]
![image](https://github.com/U1805/momotalk/assets/170069732/f0af7de1-2688-4659-b738-a9d5c01929db)
the browser did not display zoom level correctly, but yeah things are good now, default zoom dont give notice anymore
ヾ(≧▽≦*)o.

**Comment by U1805** [comment]
yes, this calculation method seems to be inaccurate in Edge for some reason. that's also why it notify user even if the browser is set to 100% zoom.

**Comment by DrunkenPipe** [comment]
alright, case closed (～￣▽￣)～
