### ISSUE TITLE
download as exe or apk

### ISSUE THREAD

**Issue by ShaLangBaiZi0420** [U1805/momotalk#35]
你好大佬. 
19岁, 是学生. 
thank you for reading this issure.
Recently I am trying hard to make your masterpiece into a downloadable file and execute it as an .exe.
but it occurs me that maybe it would be better if u can do it yourself, or I can help someway. 
It would be tremendously good if we (or, us) could use the fantastic momotalk without the limit of WLAN and , most significantly, **the copyright issues.**
Thank you again and wish you a good day. 
sincerely.

**Comment by U1805** [comment]
Hello,

First, thank you for your interest in developing this project further. Regarding copyright-related matters, I have already addressed them at the bottom of the readme file. If you are referring to the license, please refer to issue #15. 

I can try to assist you with your development, but I do not intend to package this web application into an .exe or .apk file.

1. If you want to package this web application into an APK file, I recommend using [a similar project](https://github.com/Eynnzerr/YuukaTalk) that already provides an APK. My experience in mobile web development is limited, and I cannot guarantee the functionality of the mobile version of this project now. It may require several iterations to become fully functional.

2. Regarding packaging this web application into a desktop executable file, I don't believe it is necessary. As you can see, this application doesn't rely on the local file system or system permissions. It is simply a tool for generating images, and the website's files are only a few dozen KB (excluding font files). Packaging such a simple web page into a program would be redundant and bloated.

**Comment by U1805** [comment]
> use the fantastic momotalk without the limit of WLAN

I don't quite understand this requirement. Going offline means you won't be able to conveniently add resources and update code versions as the game updates. **I don't want users to have to frequently update an app just to use new characters.**

Offline functionality mainly speeds up the initial startup and image loading. So, You can also achieve faster resource loading by forking the repository, replacing the resource paths with your personal server's resources and deploying it. (Currently, most image resources in the application are directly linked from major wikis)
