### ISSUE TITLE
How to download and run as an app in window

### ISSUE THREAD

**Issue by Iceleaf1018** [U1805/momotalk#38]
Literally im interested in this feature and its pity since i dont know how to use github and use this code without opening chrome or this github. May i have an answer that is it yes or no if it can run as an app? If can, may i know how?

**Comment by U1805** [comment]
Thanks for your interest! You can use the [PWA](https://answers.microsoft.com/en-us/microsoftedge/forum/all/creating-web-apps-in-microsoft-edge/bcc02ba3-9fbc-4f3f-b854-741b792f6e9b) feature in Microsoft Edge to get a desktop app-like experience with the web application. This might give you the experience you're looking for. (σ′▽‵)′▽‵)σ

If you need a fully standalone app, you would have to build it with tools like Electron for desktop or Cordova/Capacitor for mobile. Currently, I don't have plans to build the project into an app, but I'll keep your feedback in mind for future updates.
